	
--set statistics io,time on
-- INDICES DE PERFORMANCES USADOS NA VIEW DE CONSULTA CHAVE NFE
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2010_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2010_001
		ON [dbo].[SF2010] ([F2_CHVNFE],[F2_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2020_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2020_001
		ON [dbo].[SF2020] ([F2_CHVNFE],[F2_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2030_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2030_001
		ON [dbo].[SF2030] ([F2_CHVNFE],[F2_EMISSAO],[D_E_L_E_T_])	
	END


IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2040_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2040_001
		ON [dbo].[SF2040] ([F2_CHVNFE],[F2_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2050_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2050_001
		ON [dbo].[SF2050] ([F2_CHVNFE],[F2_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2060_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2060_001
		ON [dbo].[SF2060] ([F2_CHVNFE],[F2_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2070_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2070_001
		ON [dbo].[SF2070] ([F2_CHVNFE],[F2_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF1010_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF1010_001
		ON [dbo].[SF1010] ([F1_CHVNFE],[F1_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF1020_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF1020_001
		ON [dbo].[SF1020] ([F1_CHVNFE],[F1_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF1030_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF1030_001
		ON [dbo].[SF1030] ([F1_CHVNFE],[F1_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF1040_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF1040_001
		ON [dbo].[SF1040] ([F1_CHVNFE],[F1_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF1050_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF1050_001
		ON [dbo].[SF1050] ([F1_CHVNFE],[F1_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF1060_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF1060_001
		ON [dbo].[SF1060] ([F1_CHVNFE],[F1_EMISSAO],[D_E_L_E_T_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF1070_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF1070_001
		ON [dbo].[SF1070] ([F1_CHVNFE],[F1_EMISSAO],[D_E_L_E_T_])
	END

-- INDICES DE PERFORMANCES USADOS NA VIEW DE CONSULTA CHAVE NFE
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC5010_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC5010_001
		ON [dbo].SC5010([C5_TIPO],[C5_XTPPED]) INCLUDE ([C5_FILIAL],[C5_NUM],[C5_CLIENTE],[C5_TRANSP],[C5_EMISSAO])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC5020_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC5020_001
		ON [dbo].SC5020([C5_TIPO],[C5_XTPPED]) INCLUDE ([C5_FILIAL],[C5_NUM],[C5_CLIENTE],[C5_TRANSP],[C5_EMISSAO])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC5030_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC5030_001
		ON [dbo].SC5030([C5_TIPO],[C5_XTPPED]) INCLUDE ([C5_FILIAL],[C5_NUM],[C5_CLIENTE],[C5_TRANSP],[C5_EMISSAO])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC5040_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC5040_001
		ON [dbo].SC5040([C5_TIPO],[C5_XTPPED]) INCLUDE ([C5_FILIAL],[C5_NUM],[C5_CLIENTE],[C5_TRANSP],[C5_EMISSAO])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC5050_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC5050_001
		ON [dbo].SC5050([C5_TIPO],[C5_XTPPED]) INCLUDE ([C5_FILIAL],[C5_NUM],[C5_CLIENTE],[C5_TRANSP],[C5_EMISSAO])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC5060_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC5060_001
		ON [dbo].SC5060([C5_TIPO],[C5_XTPPED]) INCLUDE ([C5_FILIAL],[C5_NUM],[C5_CLIENTE],[C5_TRANSP],[C5_EMISSAO])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC5070_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC5070_001
		ON [dbo].SC5070([C5_TIPO],[C5_XTPPED]) INCLUDE ([C5_FILIAL],[C5_NUM],[C5_CLIENTE],[C5_TRANSP],[C5_EMISSAO])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SM2010_001')
	BEGIN
        CREATE NONCLUSTERED INDEX K_P_SM2010_001
        ON [dbo].[SM2010] ([D_E_L_E_T_],[M2_DATA])
        INCLUDE (M2_MOEDA2 , M2_MOEDA3 , M2_MOEDA4 , M2_MOEDA5)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SM2020_001')
	BEGIN
        CREATE NONCLUSTERED INDEX K_P_SM2020_001
        ON [dbo].[SM2020] ([D_E_L_E_T_],[M2_DATA])
        INCLUDE (M2_MOEDA2 , M2_MOEDA3 , M2_MOEDA4 , M2_MOEDA5)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SM2030_001')
	BEGIN
        CREATE NONCLUSTERED INDEX K_P_SM2030_001
        ON [dbo].[SM2030] ([D_E_L_E_T_],[M2_DATA])
        INCLUDE (M2_MOEDA2 , M2_MOEDA3 , M2_MOEDA4 , M2_MOEDA5)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SM2040_001')
	BEGIN
        CREATE NONCLUSTERED INDEX K_P_SM2040_001
        ON [dbo].[SM2040] ([D_E_L_E_T_],[M2_DATA])
        INCLUDE (M2_MOEDA2 , M2_MOEDA3 , M2_MOEDA4 , M2_MOEDA5)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SM2050_001')
	BEGIN
        CREATE NONCLUSTERED INDEX K_P_SM2050_001
        ON [dbo].[SM2050] ([D_E_L_E_T_],[M2_DATA])
        INCLUDE (M2_MOEDA2 , M2_MOEDA3 , M2_MOEDA4 , M2_MOEDA5)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SM2060_001')
	BEGIN
        CREATE NONCLUSTERED INDEX K_P_SM2060_001
        ON [dbo].[SM2060] ([D_E_L_E_T_],[M2_DATA])
        INCLUDE (M2_MOEDA2 , M2_MOEDA3 , M2_MOEDA4 , M2_MOEDA5)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SM2070_001')
	BEGIN
        CREATE NONCLUSTERED INDEX K_P_SM2070_001
        ON [dbo].[SM2070] ([D_E_L_E_T_],[M2_DATA])
        INCLUDE (M2_MOEDA2 , M2_MOEDA3 , M2_MOEDA4 , M2_MOEDA5)
	END
	
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE1010_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE1010_001
		ON [dbo].SE1010 (E1_CLIENTE,E1_LOJA,E1_FILIAL,D_E_L_E_T_) 
						INCLUDE(E1_VALOR,E1_SALDO,E1_VALLIQ,E1_VLCRUZ,E1_MOEDA,E1_EMISSAO,E1_TIPO, 
						 E1_VENCTO ,E1_VENCREA,E1_BAIXA,E1_PREFIXO,E1_NUM,E1_PARCELA,E1_ORIGEM,E1_FATURA,E1_MSFIL, 
						 E1_PEDIDO ,E1_SERIE )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE1020_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE1020_001
		ON [dbo].SE1020 (E1_CLIENTE,E1_LOJA,E1_FILIAL,D_E_L_E_T_) 
						INCLUDE(E1_VALOR,E1_SALDO,E1_VALLIQ,E1_VLCRUZ,E1_MOEDA,E1_EMISSAO,E1_TIPO, 
						 E1_VENCTO ,E1_VENCREA,E1_BAIXA,E1_PREFIXO,E1_NUM,E1_PARCELA,E1_ORIGEM,E1_FATURA,E1_MSFIL, 
						 E1_PEDIDO ,E1_SERIE )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE1030_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE1030_001
		ON [dbo].SE1030 (E1_CLIENTE,E1_LOJA,E1_FILIAL,D_E_L_E_T_) 
						INCLUDE(E1_VALOR,E1_SALDO,E1_VALLIQ,E1_VLCRUZ,E1_MOEDA,E1_EMISSAO,E1_TIPO, 
						 E1_VENCTO ,E1_VENCREA,E1_BAIXA,E1_PREFIXO,E1_NUM,E1_PARCELA,E1_ORIGEM,E1_FATURA,E1_MSFIL, 
						 E1_PEDIDO ,E1_SERIE )
	END
	
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE1040_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE1040_001
		ON [dbo].SE1040 (E1_CLIENTE,E1_LOJA,E1_FILIAL,D_E_L_E_T_) 
						INCLUDE(E1_VALOR,E1_SALDO,E1_VALLIQ,E1_VLCRUZ,E1_MOEDA,E1_EMISSAO,E1_TIPO, 
						 E1_VENCTO ,E1_VENCREA,E1_BAIXA,E1_PREFIXO,E1_NUM,E1_PARCELA,E1_ORIGEM,E1_FATURA,E1_MSFIL, 
						 E1_PEDIDO ,E1_SERIE )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE1050_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE1050_001
		ON [dbo].SE1050 (E1_CLIENTE,E1_LOJA,E1_FILIAL,D_E_L_E_T_) 
						INCLUDE(E1_VALOR,E1_SALDO,E1_VALLIQ,E1_VLCRUZ,E1_MOEDA,E1_EMISSAO,E1_TIPO, 
						 E1_VENCTO ,E1_VENCREA,E1_BAIXA,E1_PREFIXO,E1_NUM,E1_PARCELA,E1_ORIGEM,E1_FATURA,E1_MSFIL, 
						 E1_PEDIDO ,E1_SERIE )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE1060_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE1060_001
		ON [dbo].SE1060 (E1_CLIENTE,E1_LOJA,E1_FILIAL,D_E_L_E_T_) 
						INCLUDE(E1_VALOR,E1_SALDO,E1_VALLIQ,E1_VLCRUZ,E1_MOEDA,E1_EMISSAO,E1_TIPO, 
						 E1_VENCTO ,E1_VENCREA,E1_BAIXA,E1_PREFIXO,E1_NUM,E1_PARCELA,E1_ORIGEM,E1_FATURA,E1_MSFIL, 
						 E1_PEDIDO ,E1_SERIE )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE1070_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE1070_001
		ON [dbo].SE1070 (E1_CLIENTE,E1_LOJA,E1_FILIAL,D_E_L_E_T_) 
						INCLUDE(E1_VALOR,E1_SALDO,E1_VALLIQ,E1_VLCRUZ,E1_MOEDA,E1_EMISSAO,E1_TIPO, 
						 E1_VENCTO ,E1_VENCREA,E1_BAIXA,E1_PREFIXO,E1_NUM,E1_PARCELA,E1_ORIGEM,E1_FATURA,E1_MSFIL, 
						 E1_PEDIDO ,E1_SERIE )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2010_006')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2010_006
				ON [dbo].SF2010 (F2_FILIAL,F2_CLIENTE,F2_LOJA,F2_DOC,F2_SERIE,D_E_L_E_T_) 
								INCLUDE( F2_VALFAT )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2020_006')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2020_006
				ON [dbo].SF2020 (F2_FILIAL,F2_CLIENTE,F2_LOJA,F2_DOC,F2_SERIE,D_E_L_E_T_) 
								INCLUDE( F2_VALFAT )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2030_006')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2030_006
				ON [dbo].SF2030 (F2_FILIAL,F2_CLIENTE,F2_LOJA,F2_DOC,F2_SERIE,D_E_L_E_T_) 
								INCLUDE( F2_VALFAT )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2040_006')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2040_006
				ON [dbo].SF2040 (F2_FILIAL,F2_CLIENTE,F2_LOJA,F2_DOC,F2_SERIE,D_E_L_E_T_) 
								INCLUDE( F2_VALFAT )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2050_006')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2050_006
				ON [dbo].SF2050 (F2_FILIAL,F2_CLIENTE,F2_LOJA,F2_DOC,F2_SERIE,D_E_L_E_T_) 
								INCLUDE( F2_VALFAT )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2060_006')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2060_006
				ON [dbo].SF2060 (F2_FILIAL,F2_CLIENTE,F2_LOJA,F2_DOC,F2_SERIE,D_E_L_E_T_) 
								INCLUDE( F2_VALFAT )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SF2070_006')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SF2070_006
				ON [dbo].SF2070 (F2_FILIAL,F2_CLIENTE,F2_LOJA,F2_DOC,F2_SERIE,D_E_L_E_T_) 
								INCLUDE( F2_VALFAT )
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE5010_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE5010_001
		ON dbo.SE5010 (E5_FILIAL,E5_PREFIXO,E5_NUMERO,E5_PARCELA,E5_TIPO,E5_CLIFOR,E5_LOJA,D_E_L_E_T_)
		INCLUDE (E5_TIPODOC,E5_SITUACA)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE5020_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE5020_001
		ON dbo.SE5020 (E5_FILIAL,E5_PREFIXO,E5_NUMERO,E5_PARCELA,E5_TIPO,E5_CLIFOR,E5_LOJA,D_E_L_E_T_)
		INCLUDE (E5_TIPODOC,E5_SITUACA)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE5030_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE5030_001
		ON dbo.SE5030 (E5_FILIAL,E5_PREFIXO,E5_NUMERO,E5_PARCELA,E5_TIPO,E5_CLIFOR,E5_LOJA,D_E_L_E_T_)
		INCLUDE (E5_TIPODOC,E5_SITUACA)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE5040_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE5040_001
		ON dbo.SE5040 (E5_FILIAL,E5_PREFIXO,E5_NUMERO,E5_PARCELA,E5_TIPO,E5_CLIFOR,E5_LOJA,D_E_L_E_T_)
		INCLUDE (E5_TIPODOC,E5_SITUACA)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE5050_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE5050_001
		ON dbo.SE5050 (E5_FILIAL,E5_PREFIXO,E5_NUMERO,E5_PARCELA,E5_TIPO,E5_CLIFOR,E5_LOJA,D_E_L_E_T_)
		INCLUDE (E5_TIPODOC,E5_SITUACA)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE5060_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE5060_001
		ON dbo.SE5060 (E5_FILIAL,E5_PREFIXO,E5_NUMERO,E5_PARCELA,E5_TIPO,E5_CLIFOR,E5_LOJA,D_E_L_E_T_)
		INCLUDE (E5_TIPODOC,E5_SITUACA)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SE5070_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SE5070_001
		ON dbo.SE5070 (E5_FILIAL,E5_PREFIXO,E5_NUMERO,E5_PARCELA,E5_TIPO,E5_CLIFOR,E5_LOJA,D_E_L_E_T_)
		INCLUDE (E5_TIPODOC,E5_SITUACA)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SA1010_002')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SA1010_002
		ON [dbo].[SA1010] ([A1_FILIAL],[D_E_L_E_T_],[A1_COD],[A1_LOJA],[R_E_C_N_O_])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SBF040_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SBF040_001
		ON [dbo].[SBF040] ([BF_FILIAL],[BF_LOCAL],[D_E_L_E_T_])
		INCLUDE ([BF_PRODUTO],[BF_LOCALIZ],[BF_QUANT],[BF_EMPENHO])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SD3010_016')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SD3010_016
		ON [dbo].[SD3010] (D3_FILIAL,D3_ESTORNO,D3_OBSERVA,D_E_L_E_T_)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SD3020_016')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SD3020_016
		ON [dbo].[SD3020] (D3_FILIAL,D3_ESTORNO,D3_OBSERVA,D_E_L_E_T_)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SD3030_016')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SD3030_016
		ON [dbo].[SD3030] (D3_FILIAL,D3_ESTORNO,D3_OBSERVA,D_E_L_E_T_)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SD3040_016')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SD3040_016
		ON [dbo].[SD3040] (D3_FILIAL,D3_ESTORNO,D3_OBSERVA,D_E_L_E_T_)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SD3050_016')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SD3050_016
		ON [dbo].[SD3050] (D3_FILIAL,D3_ESTORNO,D3_OBSERVA,D_E_L_E_T_)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SD3060_016')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SD3060_016
		ON [dbo].[SD3060] (D3_FILIAL,D3_ESTORNO,D3_OBSERVA,D_E_L_E_T_)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SD3070_016')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SD3070_016
		ON [dbo].[SD3070] (D3_FILIAL,D3_ESTORNO,D3_OBSERVA,D_E_L_E_T_)
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SZF010_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SZF010_001
		ON [dbo].[SZF010] ([ZF_FILIAL],[ZF_CODIGO],[ZF_USUACOD],[ZF_DATA],[D_E_L_E_T_])
		INCLUDE ([ZF_PEDIDO],[ZF_USUANOM],[ZF_HORA],[ZF_OBS])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SZF020_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SZF020_001
		ON [dbo].[SZF020] ([ZF_FILIAL],[ZF_CODIGO],[ZF_USUACOD],[ZF_DATA],[D_E_L_E_T_])
		INCLUDE ([ZF_PEDIDO],[ZF_USUANOM],[ZF_HORA],[ZF_OBS])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SZF030_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SZF030_001
		ON [dbo].[SZF030] ([ZF_FILIAL],[ZF_CODIGO],[ZF_USUACOD],[ZF_DATA],[D_E_L_E_T_])
		INCLUDE ([ZF_PEDIDO],[ZF_USUANOM],[ZF_HORA],[ZF_OBS])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SZF040_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SZF040_001
		ON [dbo].[SZF040] ([ZF_FILIAL],[ZF_CODIGO],[ZF_USUACOD],[ZF_DATA],[D_E_L_E_T_])
		INCLUDE ([ZF_PEDIDO],[ZF_USUANOM],[ZF_HORA],[ZF_OBS])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SZF050_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SZF050_001
		ON [dbo].[SZF050] ([ZF_FILIAL],[ZF_CODIGO],[ZF_USUACOD],[ZF_DATA],[D_E_L_E_T_])
		INCLUDE ([ZF_PEDIDO],[ZF_USUANOM],[ZF_HORA],[ZF_OBS])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SZF060_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SZF060_001
		ON [dbo].[SZF060] ([ZF_FILIAL],[ZF_CODIGO],[ZF_USUACOD],[ZF_DATA],[D_E_L_E_T_])
		INCLUDE ([ZF_PEDIDO],[ZF_USUANOM],[ZF_HORA],[ZF_OBS])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SZF070_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SZF070_001
		ON [dbo].[SZF070] ([ZF_FILIAL],[ZF_CODIGO],[ZF_USUACOD],[ZF_DATA],[D_E_L_E_T_])
		INCLUDE ([ZF_PEDIDO],[ZF_USUANOM],[ZF_HORA],[ZF_OBS])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_Z06010_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_Z06010_001
		ON [dbo].[Z06010] ([Z06_CODIGO],[D_E_L_E_T_])
		INCLUDE ([Z06_FILIAL],[Z06_ARQUIV],[Z06_DATA],[Z06_HORA],[Z06_STATUS])
	END


IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SD3020_017')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SD3020_017
		ON [dbo].[SD3040] ([D3_FILIAL],[D3_OP],[D3_EMISSAO],[D3_ESTORNO],[D_E_L_E_T_])
		INCLUDE ([D3_COD],[D3_QUANT],[D3_CF],[D3_CUSTO1])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SB9040_007')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SB9040_007
		ON [dbo].[SB9040] ([D_E_L_E_T_])
		INCLUDE ([B9_FILIAL],[B9_COD],[B9_LOCAL],[B9_DATA],[B9_QINI],[B9_VINI1],[B9_CM1])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC0010_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC0010_001
		ON [dbo].[SC0010] ([C0_TIPO],[D_E_L_E_T_])
		INCLUDE ([C0_FILIAL],[C0_NUM],[C0_DOCRES],[C0_PRODUTO],[C0_LOCAL])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC0020_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC0020_001
		ON [dbo].[SC0020] ([C0_TIPO],[D_E_L_E_T_])
		INCLUDE ([C0_FILIAL],[C0_NUM],[C0_DOCRES],[C0_PRODUTO],[C0_LOCAL])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC0030_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC0030_001
		ON [dbo].[SC0030] ([C0_TIPO],[D_E_L_E_T_])
		INCLUDE ([C0_FILIAL],[C0_NUM],[C0_DOCRES],[C0_PRODUTO],[C0_LOCAL])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC0040_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC0040_001
		ON [dbo].[SC0040] ([C0_TIPO],[D_E_L_E_T_])
		INCLUDE ([C0_FILIAL],[C0_NUM],[C0_DOCRES],[C0_PRODUTO],[C0_LOCAL])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC0050_001') and EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='SC0050')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC0050_001
		ON [dbo].[SC0050] ([C0_TIPO],[D_E_L_E_T_])
		INCLUDE ([C0_FILIAL],[C0_NUM],[C0_DOCRES],[C0_PRODUTO],[C0_LOCAL])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC0060_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC0060_001
		ON [dbo].[SC0060] ([C0_TIPO],[D_E_L_E_T_])
		INCLUDE ([C0_FILIAL],[C0_NUM],[C0_DOCRES],[C0_PRODUTO],[C0_LOCAL])
	END

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'K_P_SC0070_001')
	BEGIN
		CREATE NONCLUSTERED INDEX K_P_SC0070_001
		ON [dbo].[SC0070] ([C0_TIPO],[D_E_L_E_T_])
		INCLUDE ([C0_FILIAL],[C0_NUM],[C0_DOCRES],[C0_PRODUTO],[C0_LOCAL])
	END

